# config for image prompt multi-view diffusion
parametrization: "eps"

scheduler_config:
  target: model_lib.ldm.lr_scheduler.LambdaLinearScheduler
  params:
    warm_up_steps: [ 1000 ]
    cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
    f_start: [ 1.e-6 ]
    f_max: [ 1. ]
    f_min: [ 1. ]

unet_config:
  target: model_lib.ldm.modules.diffusionmodules.openaimodel.MultiViewUNetModel
  params:
    image_size: 32 # unused
    in_channels: 4
    out_channels: 4
    model_channels: 320
    attention_resolutions: [ 4, 2, 1 ]
    num_res_blocks: 2
    channel_mult: [ 1, 2, 4, 4 ]
    num_head_channels: 64 # need to fix for flash-attn
    use_spatial_transformer: True
    use_linear_in_transformer: True
    transformer_depth: 1
    context_dim: 1024
    use_checkpoint: False
    legacy: False
    with_ip: True
    ip_dim: 16 # ip token length
    ip_mode: "local_resample"
    frame_num: 5

vae_config:
  target: model_lib.ldm.autoencoder.AutoencoderKL
  params:
    embed_dim: 4
    monitor: val/rec_loss
    ddconfig:
      #attn_type: "vanilla-xformers"
      double_z: true
      z_channels: 4
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: torch.nn.Identity

clip_config:
  target: model_lib.ldm.modules.encoders.modules.FrozenOpenCLIPEmbedder
  params:
    freeze: True
    layer: "penultimate"
    encode_image: True
    ip_mode: "local_resample"
