name: "fantasia3d"
tag: "debug"
exp_root_dir: "outputs"
seed: 0


data_type: "random-camera-datamodule"
data:
  batch_size: 2
  width: 512
  height: 512
  camera_distance_range: [3, 3]
  fovy_range: [25, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  elevation_range: [-15, 45]
  azimuth_range: [-180, 180]

system_type: "fantasia3d-system"
system:
  geometry_type: "implicit-sdf"
  geometry:
    isosurface_optimize_grid: false
    isosurface_resolution: 64
    shape_init: sphere
    shape_init_params: 0.5


  prompt_processor_type: "dreamfusion-prompt-processor"
  prompt_processor:
    prompt: "a delicious hamburger"
    view_dependent_prompting: false
  
  guidance_type: "stable-diffusion-guidance"
  guidance:
    half_precision_weights: true
    guidance_scale: 30.
    max_step_percent: 0.5
  
  loss:
    lambda_sdf: 1.
    lambda_sds: 1.
    lambda_sdf_reg: 0.0

  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [0.9, 0.99]
      eps: 1.e-15


trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 100
  limit_val_batches: 1
  enable_progress_bar: true
  precision: 16

checkpoint:
  # save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
