name: "zero123"
tag: "${data.random_camera.height}_${rmspace:${basename:${data.image_path}},_}_finite"
exp_root_dir: "outputs"
seed: 0

data_type: "single-image-datamodule"
data: # threestudio/data/image.py -> SingleImageDataModuleConfig
  image_path: ./load/images/lego_batman_rgba.png
  height: 96
  width: 96
  default_elevation_deg: 0.0
  default_azimuth_deg: 0.0
  default_camera_distance: 3.2
  default_fovy_deg: 20.0
  random_camera:  # threestudio/data/uncond.py -> RandomCameraDataModuleConfig
    height: 64
    width: 64
    eval_height: 256
    eval_width: 256
    batch_size: 1
    eval_batch_size: 1
    elevation_range: [-10, 90]
    azimuth_range: [-180, 180]
    camera_distance_range: [3.0, 3.5]
    fovy_range: [20., 20.]  # Zero123 has fixed fovy
    camera_perturb: 0.0
    center_perturb: 0.0
    up_perturb: 0.0
    light_position_perturb: 1.0
    light_distance_range: [4.5, 6.0]
    eval_elevation_deg: ${data.default_elevation_deg}
    eval_camera_distance: ${data.default_camera_distance}
    eval_fovy_deg: ${data.default_fovy_deg}
    light_sample_strategy: "dreamfusion"
    batch_uniform_azimuth: False
    n_val_views: 30
    n_test_views: 120

system_type: "zero123-system"
system:
  geometry_type: "implicit-volume"
  geometry:
    isosurface_method: "mc-cpu"
    isosurface_resolution: 128
    isosurface_threshold: 5.0
    normal_type: "finite_difference"
    finite_difference_normal_eps: 0.001
    mlp_network_config:
      otype: "VanillaMLP"
      activation: "ReLU"
      output_activation: "none"
      n_neurons: 64
      n_hidden_layers: 2

  material_type: "diffuse-with-point-light-material"
  material:
    diffuse_prob: 1.0
    textureless_prob: 0.2
    ambient_light_color: [1.0, 1.0, 1.0]
    diffuse_light_color: [0.0, 0.0, 0.0]
    ambient_only_steps: ${system.freq.ref_only_steps}

  background_type: "neural-environment-map-background"
  background:
    dir_encoding_config:
      otype: ProgressiveBandFrequency
      n_frequencies: 6
    mlp_network_config:
      otype: VanillaMLP
      n_neurons: 32
      n_hidden_layers: 1
      activation: "ReLU"

  renderer_type: "nerf-volume-renderer"
  renderer:
    num_samples_per_ray: 512
    lambda_normal_smooth: ${system.loss.lambda_normal_smooth}
    lambda_3d_normal_smooth: ${system.loss.lambda_3d_normal_smooth}

  prompt_processor_type: "zero123-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: ""
    prompt: ""

  guidance_type: "zero123-guidance"
  guidance:
    pretrained_model_name_or_path: "./load/zero123/105000.ckpt"
    pretrained_config: "./load/zero123/sd-objaverse-finetune-c_concat-256.yaml"
    cond_image_path: ${data.image_path}
    cond_elevation_deg: ${data.default_elevation_deg}
    cond_azimuth_deg: ${data.default_azimuth_deg}
    cond_camera_distance: ${data.default_camera_distance}
    guidance_scale: 5.
    min_step_percent: 0.02
    max_step_percent: 0.98

  freq:
    n_ref: 2
    ref_only_steps: 0

  loss:
    lambda_sds: 1.
    lambda_rgb: 1000.
    lambda_mask: 500.
    lambda_depth: 10.
    lambda_normal_smooth: 0.0
    lambda_3d_normal_smooth: 10.0
    lambda_orient: 1.0
    lambda_sparsity: 0.0
    lambda_opaque: 0.0

  optimizer:
    name: Adan
    args:
      lr: 0.005
      max_grad_norm: 5.0
      eps: 1.e-8
      weight_decay: 2e-5
    params:
      geometry:
        lr: ${system.optimizer.args.lr}
      background:
        lr: ${system.optimizer.args.lr}

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
